#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#   ---------------------------
#   程序：百度贴吧爬虫
#   版本：1.0
#   作者：蒋宇航
#   日期：2017-5-21
#   语言：python3
#   操作：输入网址后自动只看楼主并保存到本地文件
#   功能：将楼主发布的内容打包txt存储到本地
#   ---------------------------
import string
import urllib
import re
class HTML_Tool:
    # 用非贪婪模式匹配\t或者\n或者空格或者超链接或者图片
    BgnCharToNoneRex=re.compile("(\t|\n| |<a.*?>|<img.*?>)")
    #用非贪婪模式匹配任意《》标签
    EndCharToNoneRex=re.compile("<.*?>")
    #用费贪婪模式匹配任意<p>标签
    BgnPartRex=re.compile("<p.*?>")
    CharToNewLineRex=re.compile("(<br/>|</p>|<tr>|<div>|</div>)")
    CharToNextTabRex=re.compile("<td>")
    #将一些Html的符号实体转变为原始符号
    replaceTab=[]